// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuj81XpjiroX4ufl3Jhs6qsPGYcUKx2Eg',
    appId: '1:662697512266:android:7e670ca3c88db96ed885b3',
    messagingSenderId: '662697512266',
    projectId: 'flutez-18e07',
    storageBucket: 'flutez-18e07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtcqdGwbUeaUzUf_CNaeJzJLtD10klSHU',
    appId: '1:662697512266:ios:a9cabb3c22a135f5d885b3',
    messagingSenderId: '662697512266',
    projectId: 'flutez-18e07',
    storageBucket: 'flutez-18e07.appspot.com',
    androidClientId: '662697512266-do531lipm93fk4liaj70biafmbiejb51.apps.googleusercontent.com',
    iosClientId: '662697512266-44i2j8icbomp1k3cq68i12af2smnk3bt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutez',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDclAGhlQltzJadaYEgy1Lr7h_VU5Qbsks',
    appId: '1:662697512266:web:79769770ad632487d885b3',
    messagingSenderId: '662697512266',
    projectId: 'flutez-18e07',
    authDomain: 'flutez-18e07.firebaseapp.com',
    storageBucket: 'flutez-18e07.appspot.com',
    measurementId: 'G-XV24B2Q4VY',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtcqdGwbUeaUzUf_CNaeJzJLtD10klSHU',
    appId: '1:662697512266:ios:a9cabb3c22a135f5d885b3',
    messagingSenderId: '662697512266',
    projectId: 'flutez-18e07',
    storageBucket: 'flutez-18e07.appspot.com',
    androidClientId: '662697512266-do531lipm93fk4liaj70biafmbiejb51.apps.googleusercontent.com',
    iosClientId: '662697512266-44i2j8icbomp1k3cq68i12af2smnk3bt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutez',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDclAGhlQltzJadaYEgy1Lr7h_VU5Qbsks',
    appId: '1:662697512266:web:fb51b913dd47f60bd885b3',
    messagingSenderId: '662697512266',
    projectId: 'flutez-18e07',
    authDomain: 'flutez-18e07.firebaseapp.com',
    storageBucket: 'flutez-18e07.appspot.com',
    measurementId: 'G-JMT8NR72RJ',
  );

}